### ISSUE TITLE
Tracking: Android SDK v1.0

### ISSUE THREAD

**Issue by elisealix22** [xmtp/xmtp-android#1]
### Requirements

Port `xmtp-js` to `xmtp-android` and demonstrate core functionality in a Kotlin sample app.

### Developer Preview - [Targeting March 1, 2023]

- [x] Create Kotlin package: `xmtp_proto`
    - [x] Add a Kotlin package generator to https://github.com/xmtp/proto   
    - [x] Publish to Kotlin Package Manager 
- [x] Create Kotlin library: `xmtp-android`
    - [x] Set up work repo: https://github.com/xmtp/xmtp-android
    - [x] Add authentication to match xmtp-js
    - [x] Wrap xmtp in a Kotlin-conventional `xmtp.Client` (like `xmtp-js`)
    - [x] Reproduce utility classes/methods
        - [x] Client
        - [x] ConversationV1
        - [x] ConversationV2
        - [x] Conversations
        - [x] MessageV1
        - [x] MessageV2
        - [x] PrivateKey
        - [x] PublicKey
        - [x] PrivateKeyBundleV1
        - [x] PrivateKeyBundleV2
        - [x] PublicKeyBundle
        - [x] SignedPublicKeyBundle
        - [x] Stream
        - [x] TextCodec
        - [x] CompositeCodec
        - [x] StreamAllMessages
        - [x] AttachmentCodec
    - [x] Publish library https://developer.android.com/studio/publish-library
- [x] Publish repo README covering Dev Preview features and with Dev Preview badge: https://github.com/xmtp/xmtp-android/issues/8

### GA - [Targeting March 30, 2023]

 - [ ] Integrated with a third party app
    - [x] Successfully received push notifications
 - [x] Publish repo README with GA badge
 - [x] Reference docs for SDK GA: https://github.com/xmtp/xmtp-android/issues/7

### Nice to have

- [x] Create sample app
    - [x] Use xmtp-android to demonstrate SDK (like `example-chat-react`)
        - [x] Initialize client
        - [x] List conversations
        - [x] List messages
        - [x] Send messages
        - [x] Stream conversations
        - [x] Stream messages
        - [x] Wallet Connect
         
### Decision log
- ~~Dec 5, 2022: We are **not** planning on including `conversations.streamAllMessages()` in the Kotlin SDK for now as we believe between push notifications & periodic polling it will be less useful than it was on web.~~ We added streamAllMessages() on March 8th, 2023
- Jan 18, 2023: We are targeting EthDenver for our SDK GA
