### ISSUE TITLE
Tracking: Android Group Chat - ALPHA

### ISSUE THREAD

**Issue by nplasterer** [xmtp/xmtp-android#157]
### Group Chat Alpha - [Targeting February 1, 2024]

- [ ] Reproduce utility classes/methods
  - [ ] Client
    - [x] update existing `create` method on client to also create a `FfiXmtpClient`
    - [x] Existing client should now also have a `FfiLogger`
    - [x] Have existing SigningKey extend `FfiInboxOwner` so it can be used to create both V2 and V3 clients
    - [x] If `FfiXmtpClient` exists get address from `account_address()`
    - [ ] If `FfiXmtpClient` exists store a reference to `installation_id()`
    - [x] Conversations on client should also take a `libXMTPConversations`
    - [x] If `FfiXmtpClient` exists client create should call `register_identity`
    - [ ] Ability to `list_my_installations()`
    - [ ] Ability to `revoke_installation()`
  - [ ] Conversations
    - [x] Should be able to create a group `newGroup()` -- `create_group()`
    - [x] Should be able to list just groups `listGroups` -- `libXMTPConversations.list()`
    - [x] Should be able to list an ordered list of conversations & groups `list(includeGroups: Boolean = false)`
    - [x] Should be able to stream groups `libXMTPConversations.stream()`
    - [x] Should be able to stream both conversations & groups `stream(includeGroups:Boolean = false)`
    - [x] Should be able to `sync` groups so that the libxmtp database gets updated
    - [x] Should be able to stream all messages from both groups and conversations (`streamAllMessages(includeGroups: Boolean = false)`
  - [ ] Conversation/Group methods
    - [x] Should have a unique identifier of the conversation `id()` equivalent to existing topic
    - [x] Should be able to `send()` messages of any content type
    - [x] Should be able to resync the libxmtp database `sync()`
    - [x] Should be able to list messages `find_messages()` as Decoded and Decrypted Messages
    - [x] Should be able to list members `list_members()`
    - [x] Should be able to add members `add_members()`
    - [x] Should be able to remove members `remove_members()`
    - [x] Should be able to stream messages `stream()`
    - [ ] Should be able to leave a group `leave()`
    - [x] Can check if a message can be sent `can_message()`
- [ ] Publish repo README covering Dev Preview features and with Dev Preview badge

### Docs
Docs are currently being drafted documents for a PR. You can check the progress made so far by visiting the [preview link](https://junk-range-possible-git-groupchats-xmtp-labs.vercel.app/docs/build/groups). For more information on the PR itself, you can check https://github.com/xmtp/xmtp-dot-org/pull/650.

### GA - [Targeting March 30, 2024]

 - [ ] Integrated with a third party app
    - [ ] Successfully received push notifications
 - [ ] Publish repo README with GA badge
 - [ ] Reference docs for SDK GA

### Nice to have

- [ ] Create sample app
    - [ ] Use SDK to demonstrate
        - [x] Initialize client
        - [x] List conversations
        - [x] List messages
        - [x] Send messages
        - [x] Stream conversations
        - [x] Stream messages
        - [x] Wallet Connect
        - [x] Group Chat
          - [x] send messages (any content type)
          - [ ] add member
          - [ ] remove member
          - [ ] list members
          - [ ] leave
