### ISSUE TITLE
Tracking: Group Chat - PROD (Android)

### ISSUE THREAD

**Issue by nplasterer** [xmtp/xmtp-android#198]
### Must have
- [x] Group Consent
- [x] Push Notifications https://github.com/xmtp/libxmtp/issues/527
- [x] Filter out group message kind https://github.com/xmtp/libxmtp/issues/522
- [x] Who added me in a group https://github.com/xmtp/xmtp-android/issues/200
- [x] Message send state https://github.com/xmtp/libxmtp/issues/516
  - [x] #207
- [x] Group Chat Names https://github.com/xmtp/libxmtp/issues/548
  - [ ] Admin roles built on mutable permission scheme https://github.com/orgs/xmtp/projects/11/views/3#
- [x] Streaming 
  - [x] #205
  - [x] #206
- [x] Inbox ID Consent

### Nice to have
- [ ] Ability to `list_my_installations()`
- [x] Ability to list current installation Id
- [ ] Ability to `revoke_installation()`
- [ ] Stream Groups (groups and convos) https://github.com/xmtp/libxmtp/issues/504
- [ ] Leave https://github.com/xmtp/libxmtp/issues/441
- [ ] #208
- [ ] HMACs https://github.com/xmtp/libxmtp/issues/422
